name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O la rama que uses como principal
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos para el GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permite un solo despliegue concurrente, cancelando ejecuciones anteriores/pendientes.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Puedes ajustar la versión de Node si es necesario

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8 # O la versión de pnpm que estés utilizando

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build # Esto ejecutará 'next build && next export'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube el contenido de la carpeta 'out'
          path: './out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 